CREATE TABLE `COORDINATOR_INFO` (
  `SERVER_ID` int(11) NOT NULL,
  `CHECKPOINT` bigint(20) NOT NULL,
  `MAX_UUID` bigint(20) NOT NULL,
  PRIMARY KEY (`SERVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `COORDINATOR_LOG` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TRX_ID` bigint(20) NOT NULL,
  `TRX_STATUS` tinyint(4) NOT NULL,
  `TRX_TIMESTAMP` bigint(20) NOT NULL,
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`,`TRX_TIMESTAMP`),
  KEY `IDX_TIMESTAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE(`TRX_TIMESTAMP`)(
   PARTITION p20141010 VALUES LESS THAN (1412870400000) ENGINE = InnoDB
);




CREATE TABLE `HEURISTIC_TRX_INFO` (
  `TRX_ID` bigint(20) NOT NULL,
  `TRX_ACTION` tinyint(4) NOT NULL,
  `TRX_HEURISTIC_CODE` smallint(6) NOT NULL,
  `TRX_TIMESTAMP` bigint(20) NOT NULL,
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (`TRX_ID`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

