CREATE TABLE `COORDINATOR_INFO` (
  `ServerId` int(11) NOT NULL DEFAULT '0',
  `CHECKPOINT` bigint(20) NOT NULL,
  PRIMARY KEY (`ServerId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `COORDINATOR_LOG` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TRX_ID` bigint(20) DEFAULT NULL,
  `TRX_STATUS` tinyint(4) DEFAULT NULL,
  `TRX_TIMESTAMP` bigint(20) NOT NULL DEFAULT '0',
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`,`TRX_TIMESTAMP`),
  KEY `IDX_TIMESTAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `HEURISTIC_TRX_INFO` (
  ` TRX_ID` bigint(20) NOT NULL DEFAULT '0',
  `TRX_ACTION` tinyint(4) DEFAULT NULL,
  `TRX_HEURISTIC_CODE` smallint(6) DEFAULT NULL,
  `TRX_TIMESTAMP` bigint(20) DEFAULT NULL,
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (` TRX_ID`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

