CREATE TABLE `EXPIRE_TRX_INFO` (
  `TRX_ID` bigint(20) NOT NULL,
  `TRX_ACTION` tinyint(4) NOT NULL,
  `TRX_TIMESTAMP` bigint(20) NOT NULL,
  PRIMARY KEY (`TRX_ID`,`TRX_TIMESTAMP`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE(`TRX_TIMESTAMP`)(
   PARTITION p20141010 VALUES LESS THAN (1412870400000) ENGINE = InnoDB
);


CREATE TABLE `HEURISTIC_TRX_INFO` (
  `TRX_ID` bigint(20) NOT NULL,
  `TRX_ACTION` tinyint(4) NOT NULL,
  `TRX_HEURISTIC_CODE` smallint(6) NOT NULL,
  `TRX_TIMESTAMP` bigint(20) NOT NULL,
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (`TRX_ID`,`TRX_TIMESTAMP`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE(`TRX_TIMESTAMP`)(
  PARTITION p20141010 VALUES LESS THAN (1412870400000) ENGINE = InnoDB
);


CREATE TABLE `SERVER_INFO` (
  `SERVER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SERVER_IP` varchar(25) NOT NULL,
  `RDS_IP` varchar(25) NOT NULL,
  PRIMARY KEY (`SERVER_ID`),
  UNIQUE KEY `IDX_SERVER_IP` (`SERVER_IP`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SERVER_MONITOR` (
  `MON_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SERVER_ID` int(11) NOT NULL,
  `TIMESTAMP` bigint(20) NOT NULL,
  `CUR_TRX_NUM` bigint(20) NOT NULL,
  `CUR_PROCESS_TRX_NUM` bigint(20) NOT NULL,
  `REGISTED_TRX_NUM` bigint(20) NOT NULL,
  `CONFIRM_NUM` bigint(20) NOT NULL,
  `CANCEL_NUM` bigint(20) NOT NULL,
  `EXPIRE_NUM` bigint(20) NOT NULL,
  `AVG_REGISTED_TIME` bigint(20) NOT NULL,
  `MAX_REGISTED_TIME` bigint(20) NOT NULL,
  `AVG_CONFIRM_TIME` bigint(20) NOT NULL,
  `MAX_CONFIRM_TIME` bigint(20) NOT NULL,
  `AVG_CANCEL_TIME` bigint(20) NOT NULL,
  `MAX_CANCEL_TIME` bigint(20) NOT NULL,
  PRIMARY KEY (`MON_ID`,`TIMESTAMP`),
  KEY `IDX_TIMESTAMP` (`TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
PARTITION BY RANGE(`TIMESTAMP`)(
  PARTITION p20141010 VALUES LESS THAN (1412870400000) ENGINE=InnoDB
);



