CREATE TABLE `EXPIRE_TRX_INFO` (
  ` TRX_ID` bigint(20) NOT NULL DEFAULT '0',
  `TRX_ACTION` tinyint(4) DEFAULT NULL,
  `TRX_TIMESTAMP` bigint(20) DEFAULT NULL,
  PRIMARY KEY (` TRX_ID`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `HEURISTIC_TRX_INFO` (
  ` TRX_ID` bigint(20) NOT NULL DEFAULT '0',
  `TRX_ACTION` tinyint(4) DEFAULT NULL,
  `TRX_HEURISTIC_CODE` smallint(6) DEFAULT NULL,
  `TRX_TIMESTAMP` bigint(20) DEFAULT NULL,
  `TRX_CONTENT` varbinary(4096) DEFAULT NULL,
  PRIMARY KEY (` TRX_ID`),
  KEY `IDX_TIME_STAMP` (`TRX_TIMESTAMP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SERVER_INFO` (
  `SERVER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SERVER_IP` varchar(25) DEFAULT NULL,
  `RDS_IP` varchar(25) DEFAULT NULL,
  PRIMARY KEY (`SERVER_ID`),
  UNIQUE KEY `IDX_SERVER_IP` (`SERVER_IP`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `SERVER_MONITOR` (
  `SERVER_ID` int(11) NOT NULL DEFAULT '0',
  `TIME_STAMP` bigint(20) NOT NULL DEFAULT '0',
  `CUR_TRX_NUM` bigint(20) DEFAULT NULL,
  `COMFIRM_NUM` bigint(20) DEFAULT NULL,
  `CANCEL_NUM` bigint(20) DEFAULT NULL,
  `EXPIRE_NUM` bigint(20) DEFAULT NULL,
  `AVG_CONFIRM_TIME` bigint(20) DEFAULT NULL,
  `MAX_CONFIRM_TIME` bigint(20) DEFAULT NULL,
  `AVG_CANCEL_TIME` bigint(20) DEFAULT NULL,
  `MAX_CANCEL_TIME` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`TIME_STAMP`,`SERVER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


